#pragma checksum "C:\Users\pc\Downloads\Coding-Challenge-master\Coding-Challenge-master\ClarkCodingChallenge\Views\Contacts\ContactsList.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "242ff6c0b6f31f59c26fd68e6e3ca2be523acf90"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Contacts_ContactsList), @"mvc.1.0.view", @"/Views/Contacts/ContactsList.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\pc\Downloads\Coding-Challenge-master\Coding-Challenge-master\ClarkCodingChallenge\Views\_ViewImports.cshtml"
using ClarkCodingChallenge;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\pc\Downloads\Coding-Challenge-master\Coding-Challenge-master\ClarkCodingChallenge\Views\_ViewImports.cshtml"
using ClarkCodingChallenge.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"242ff6c0b6f31f59c26fd68e6e3ca2be523acf90", @"/Views/Contacts/ContactsList.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"d067e1e9653956985e0b9a135efe012d2c0260c8", @"/Views/_ViewImports.cshtml")]
    public class Views_Contacts_ContactsList : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<ClarkCodingChallenge.Models.ContactsViewModel>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 2 "C:\Users\pc\Downloads\Coding-Challenge-master\Coding-Challenge-master\ClarkCodingChallenge\Views\Contacts\ContactsList.cshtml"
  
    ViewData["Title"] = "ContactsList";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<h1>ContactsList</h1>\r\n\r\n<table class=\"table\">\r\n    <thead>\r\n        <tr>\r\n            <th>\r\n               contacts\r\n            </th>\r\n\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");
#nullable restore
#line 18 "C:\Users\pc\Downloads\Coding-Challenge-master\Coding-Challenge-master\ClarkCodingChallenge\Views\Contacts\ContactsList.cshtml"
         foreach (var item in Model.contacts)
        {

#line default
#line hidden
#nullable disable
            WriteLiteral("            <tr>\r\n                <td>\r\n                    ");
#nullable restore
#line 22 "C:\Users\pc\Downloads\Coding-Challenge-master\Coding-Challenge-master\ClarkCodingChallenge\Views\Contacts\ContactsList.cshtml"
               Write(Html.DisplayFor(modelItem => item.LastName));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </td>\r\n                <td>\r\n                    ");
#nullable restore
#line 25 "C:\Users\pc\Downloads\Coding-Challenge-master\Coding-Challenge-master\ClarkCodingChallenge\Views\Contacts\ContactsList.cshtml"
               Write(Html.DisplayFor(modelItem => item.FirstName));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </td>\r\n                <td>\r\n                    ");
#nullable restore
#line 28 "C:\Users\pc\Downloads\Coding-Challenge-master\Coding-Challenge-master\ClarkCodingChallenge\Views\Contacts\ContactsList.cshtml"
               Write(Html.DisplayFor(modelItem => item.Email));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </td>\r\n            </tr>\r\n");
#nullable restore
#line 31 "C:\Users\pc\Downloads\Coding-Challenge-master\Coding-Challenge-master\ClarkCodingChallenge\Views\Contacts\ContactsList.cshtml"
        }

#line default
#line hidden
#nullable disable
            WriteLiteral("    </tbody>\r\n</table>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<ClarkCodingChallenge.Models.ContactsViewModel> Html { get; private set; }
    }
}
#pragma warning restore 1591
